//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SudokuGraphicCreator.Properties.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SudokuGraphicCreator.Properties.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booklet informations.
        /// </summary>
        public static string BookletInformations {
            get {
                return ResourceManager.GetString("BookletInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional, example: main, U18 or O50..
        /// </summary>
        public static string BookletInformationsCategory {
            get {
                return ResourceManager.GetString("BookletInformationsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placed in the top left corner of first booklet page..
        /// </summary>
        public static string BookletInformationsLogoOne {
            get {
                return ResourceManager.GetString("BookletInformationsLogoOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placed in the left bottom corner of first booklet page..
        /// </summary>
        public static string BookletInformationsLogoThree {
            get {
                return ResourceManager.GetString("BookletInformationsLogoThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placed in the top right corner of first booklet page..
        /// </summary>
        public static string BookletInformationsLogoTwo {
            get {
                return ResourceManager.GetString("BookletInformationsLogoTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter number.
        /// </summary>
        public static string BookletInformationsOrderNumber {
            get {
                return ResourceManager.GetString("BookletInformationsOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter time for solving, example: 30 minutes.
        /// </summary>
        public static string BookletInformationsTime {
            get {
                return ResourceManager.GetString("BookletInformationsTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The calculation is in progress....
        /// </summary>
        public static string CalculationProgress {
            get {
                return ResourceManager.GetString("CalculationProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply classic sudoku rules..
        /// </summary>
        public static string ClassicRulesShort {
            get {
                return ResourceManager.GetString("ClassicRulesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill the grid with digits 1 to 9, so that each digit appears once in every row, column and outlined box..
        /// </summary>
        public static string ClassicSudokuRules {
            get {
                return ResourceManager.GetString("ClassicSudokuRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct format.
        /// </summary>
        public static string CorrectFormat {
            get {
                return ResourceManager.GetString("CorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountOfSolutions.
        /// </summary>
        public static string CountOfSolutions {
            get {
                return ResourceManager.GetString("CountOfSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variants.
        /// </summary>
        public static string CreatingSudokuLabelVariants {
            get {
                return ResourceManager.GetString("CreatingSudokuLabelVariants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete booklet page.
        /// </summary>
        public static string DeleteBookletPage {
            get {
                return ResourceManager.GetString("DeleteBookletPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete sudoku.
        /// </summary>
        public static string DeleteSudoku {
            get {
                return ResourceManager.GetString("DeleteSudoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same digits cannot repeat on the main diagonals..
        /// </summary>
        public static string DiagonalRules {
            get {
                return ResourceManager.GetString("DiagonalRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit booklet.
        /// </summary>
        public static string EditBooklet {
            get {
                return ResourceManager.GetString("EditBooklet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit booklet informations....
        /// </summary>
        public static string EditBookletInformations {
            get {
                return ResourceManager.GetString("EditBookletInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrows.
        /// </summary>
        public static string ElemArrows {
            get {
                return ResourceManager.GetString("ElemArrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow with circle.
        /// </summary>
        public static string ElemArrowWithCircle {
            get {
                return ResourceManager.GetString("ElemArrowWithCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black circle.
        /// </summary>
        public static string ElemBlackCircle {
            get {
                return ResourceManager.GetString("ElemBlackCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold arrow.
        /// </summary>
        public static string ElemBoldArrow {
            get {
                return ResourceManager.GetString("ElemBoldArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cage.
        /// </summary>
        public static string ElemCage {
            get {
                return ResourceManager.GetString("ElemCage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        public static string ElemCharacters {
            get {
                return ResourceManager.GetString("ElemCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        public static string ElemCircle {
            get {
                return ResourceManager.GetString("ElemCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle with grey edge.
        /// </summary>
        public static string ElemCircleWithGreyEdge {
            get {
                return ResourceManager.GetString("ElemCircleWithGreyEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle with number.
        /// </summary>
        public static string ElemCircleWithNumber {
            get {
                return ResourceManager.GetString("ElemCircleWithNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grey cell.
        /// </summary>
        public static string ElemGreyCell {
            get {
                return ResourceManager.GetString("ElemGreyCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grey circle.
        /// </summary>
        public static string ElemGreyCircle {
            get {
                return ResourceManager.GetString("ElemGreyCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid.
        /// </summary>
        public static string ElemGrid {
            get {
                return ResourceManager.GetString("ElemGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string ElemLine {
            get {
                return ResourceManager.GetString("ElemLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long arrow.
        /// </summary>
        public static string ElemLongArrow {
            get {
                return ResourceManager.GetString("ElemLongArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small arrow.
        /// </summary>
        public static string ElemSmallArrow {
            get {
                return ResourceManager.GetString("ElemSmallArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        public static string ElemSquare {
            get {
                return ResourceManager.GetString("ElemSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star.
        /// </summary>
        public static string ElemStar {
            get {
                return ResourceManager.GetString("ElemStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White circle.
        /// </summary>
        public static string ElemWhiteCircle {
            get {
                return ResourceManager.GetString("ElemWhiteCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export solution.
        /// </summary>
        public static string ExportSolution {
            get {
                return ResourceManager.GetString("ExportSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First sudoku.
        /// </summary>
        public static string FirstSudoku {
            get {
                return ResourceManager.GetString("FirstSudoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to generate all graphic elements.
        /// </summary>
        public static string GenerateAllGraphicElements {
            get {
                return ResourceManager.GetString("GenerateAllGraphicElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to generate solution.
        /// </summary>
        public static string GenerateSolution {
            get {
                return ResourceManager.GetString("GenerateSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given numbers.
        /// </summary>
        public static string GivenNumbers {
            get {
                return ResourceManager.GetString("GivenNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic elements:.
        /// </summary>
        public static string GraphicElemenets {
            get {
                return ResourceManager.GetString("GraphicElemenets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halt.
        /// </summary>
        public static string Halt {
            get {
                return ResourceManager.GetString("Halt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect format.
        /// </summary>
        public static string IncorrectFormat {
            get {
                return ResourceManager.GetString("IncorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition booklet - basic informations.
        /// </summary>
        public static string InformationsForBookletTitle {
            get {
                return ResourceManager.GetString("InformationsForBookletTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input string.
        /// </summary>
        public static string InputString {
            get {
                return ResourceManager.GetString("InputString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input strings.
        /// </summary>
        public static string InputStrings {
            get {
                return ResourceManager.GetString("InputStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert given numbers.
        /// </summary>
        public static string InsertGivenNumbers {
            get {
                return ResourceManager.GetString("InsertGivenNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertion given numbers.
        /// </summary>
        public static string InsertionGivenNumberTitle {
            get {
                return ResourceManager.GetString("InsertionGivenNumberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertion graphic elements and variants.
        /// </summary>
        public static string InsertionGraphicElements {
            get {
                return ResourceManager.GetString("InsertionGraphicElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertion of new sudoku table.
        /// </summary>
        public static string InsertionOfNewSudokuTable {
            get {
                return ResourceManager.GetString("InsertionOfNewSudokuTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert new sudoku table.
        /// </summary>
        public static string InsertNewSudokuTable {
            get {
                return ResourceManager.GetString("InsertNewSudokuTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert number.
        /// </summary>
        public static string InsertNumber {
            get {
                return ResourceManager.GetString("InsertNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert solution.
        /// </summary>
        public static string InsertSolution {
            get {
                return ResourceManager.GetString("InsertSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo of competition.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About app....
        /// </summary>
        public static string MenuAboutApp {
            get {
                return ResourceManager.GetString("MenuAboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close all.
        /// </summary>
        public static string MenuCloseAll {
            get {
                return ResourceManager.GetString("MenuCloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm selection.
        /// </summary>
        public static string MenuConfirmSelection {
            get {
                return ResourceManager.GetString("MenuConfirmSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of solutions....
        /// </summary>
        public static string MenuCountOfSolutions {
            get {
                return ResourceManager.GetString("MenuCountOfSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete page....
        /// </summary>
        public static string MenuDeletePage {
            get {
                return ResourceManager.GetString("MenuDeletePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete sudoku....
        /// </summary>
        public static string MenuDeleteSudoku {
            get {
                return ResourceManager.GetString("MenuDeleteSudoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string MenuDown {
            get {
                return ResourceManager.GetString("MenuDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit booklet....
        /// </summary>
        public static string MenuEditBooklet {
            get {
                return ResourceManager.GetString("MenuEditBooklet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit sudoku....
        /// </summary>
        public static string MenuEditSudoku {
            get {
                return ResourceManager.GetString("MenuEditSudoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuEnd {
            get {
                return ResourceManager.GetString("MenuEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export....
        /// </summary>
        public static string MenuExport {
            get {
                return ResourceManager.GetString("MenuExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export file with solutions....
        /// </summary>
        public static string MenuExportFileWIthSolutions {
            get {
                return ResourceManager.GetString("MenuExportFileWIthSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic elements.
        /// </summary>
        public static string MenuGraphicElements {
            get {
                return ResourceManager.GetString("MenuGraphicElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert graphic elements and variants....
        /// </summary>
        public static string MenuInsertElemAndVariants {
            get {
                return ResourceManager.GetString("MenuInsertElemAndVariants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert given numbers....
        /// </summary>
        public static string MenuInsertGivenNumbers {
            get {
                return ResourceManager.GetString("MenuInsertGivenNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert graphic elements....
        /// </summary>
        public static string MenuInsertGraphicElem {
            get {
                return ResourceManager.GetString("MenuInsertGraphicElem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert graphic element.
        /// </summary>
        public static string MenuInsertGraphicElement {
            get {
                return ResourceManager.GetString("MenuInsertGraphicElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert new page.
        /// </summary>
        public static string MenuInsertNewPage {
            get {
                return ResourceManager.GetString("MenuInsertNewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert new sudoku....
        /// </summary>
        public static string MenuInsertNewSudoku {
            get {
                return ResourceManager.GetString("MenuInsertNewSudoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert number.
        /// </summary>
        public static string MenuInsertNumber {
            get {
                return ResourceManager.GetString("MenuInsertNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert solution....
        /// </summary>
        public static string MenuInsertSolution {
            get {
                return ResourceManager.GetString("MenuInsertSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert variant.
        /// </summary>
        public static string MenuInsertVariant {
            get {
                return ResourceManager.GetString("MenuInsertVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string MenuLeft {
            get {
                return ResourceManager.GetString("MenuLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down of the left.
        /// </summary>
        public static string MenuLeftDown {
            get {
                return ResourceManager.GetString("MenuLeftDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper left.
        /// </summary>
        public static string MenuLeftUp {
            get {
                return ResourceManager.GetString("MenuLeftUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string MenuNew {
            get {
                return ResourceManager.GetString("MenuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New size....
        /// </summary>
        public static string MenuNewSize {
            get {
                return ResourceManager.GetString("MenuNewSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New window.
        /// </summary>
        public static string MenuNewWindow {
            get {
                return ResourceManager.GetString("MenuNewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel with graphic elements.
        /// </summary>
        public static string MenuPanelWithGraphicElements {
            get {
                return ResourceManager.GetString("MenuPanelWithGraphicElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel with variants.
        /// </summary>
        public static string MenuPanelWithVariants {
            get {
                return ResourceManager.GetString("MenuPanelWithVariants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string MenuRedo {
            get {
                return ResourceManager.GetString("MenuRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset regions.
        /// </summary>
        public static string MenuResetGrid {
            get {
                return ResourceManager.GetString("MenuResetGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset selection.
        /// </summary>
        public static string MenuResetSelection {
            get {
                return ResourceManager.GetString("MenuResetSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string MenuRight {
            get {
                return ResourceManager.GetString("MenuRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down of the right.
        /// </summary>
        public static string MenuRightDown {
            get {
                return ResourceManager.GetString("MenuRightDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper right.
        /// </summary>
        public static string MenuRightUp {
            get {
                return ResourceManager.GetString("MenuRightUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MenuSave {
            get {
                return ResourceManager.GetString("MenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as....
        /// </summary>
        public static string MenuSaveAs {
            get {
                return ResourceManager.GetString("MenuSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection of region.
        /// </summary>
        public static string MenuSelectRegion {
            get {
                return ResourceManager.GetString("MenuSelectRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show help....
        /// </summary>
        public static string MenuShowHelp {
            get {
                return ResourceManager.GetString("MenuShowHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudoku with arrow over cells.
        /// </summary>
        public static string MenuSudokuArrowOverCells {
            get {
                return ResourceManager.GetString("MenuSudokuArrowOverCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudoku with cages.
        /// </summary>
        public static string MenuSudokuCage {
            get {
                return ResourceManager.GetString("MenuSudokuCage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudoku with element between two cells.
        /// </summary>
        public static string MenuSudokuElemenetBetweenTwoCells {
            get {
                return ResourceManager.GetString("MenuSudokuElemenetBetweenTwoCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudoku with element in cell.
        /// </summary>
        public static string MenuSudokuElementInCell {
            get {
                return ResourceManager.GetString("MenuSudokuElementInCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudoku graphic unique.
        /// </summary>
        public static string MenuSudokuGraphicUnique {
            get {
                return ResourceManager.GetString("MenuSudokuGraphicUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudoku with grey cells.
        /// </summary>
        public static string MenuSudokuGreyCells {
            get {
                return ResourceManager.GetString("MenuSudokuGreyCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudoku with irregular grid.
        /// </summary>
        public static string MenuSudokuIrregular {
            get {
                return ResourceManager.GetString("MenuSudokuIrregular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudoku looking like classic sudoku.
        /// </summary>
        public static string MenuSudokuLikeClassic {
            get {
                return ResourceManager.GetString("MenuSudokuLikeClassic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudoku with line over cells.
        /// </summary>
        public static string MenuSudokuLineOverCells {
            get {
                return ResourceManager.GetString("MenuSudokuLineOverCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudoku with numbers around grid.
        /// </summary>
        public static string MenuSudokuNumberAroundGrid {
            get {
                return ResourceManager.GetString("MenuSudokuNumberAroundGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string MenuUndo {
            get {
                return ResourceManager.GetString("MenuUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nahoru.
        /// </summary>
        public static string MenuUp {
            get {
                return ResourceManager.GetString("MenuUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.
        /// </summary>
        public static string MenuV {
            get {
                return ResourceManager.GetString("MenuV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variants.
        /// </summary>
        public static string MenuVariants {
            get {
                return ResourceManager.GetString("MenuVariants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string MenuWindow {
            get {
                return ResourceManager.GetString("MenuWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        public static string MenuX {
            get {
                return ResourceManager.GetString("MenuX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of competition:.
        /// </summary>
        public static string NameOfCompetition {
            get {
                return ResourceManager.GetString("NameOfCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string NameOfPlayer {
            get {
                return ResourceManager.GetString("NameOfPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of round:.
        /// </summary>
        public static string NameOfRound {
            get {
                return ResourceManager.GetString("NameOfRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string NameOfSudoku {
            get {
                return ResourceManager.GetString("NameOfSudoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New booklet.
        /// </summary>
        public static string NewBooklet {
            get {
                return ResourceManager.GetString("NewBooklet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New page.
        /// </summary>
        public static string NewPage {
            get {
                return ResourceManager.GetString("NewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New table.
        /// </summary>
        public static string NewTable {
            get {
                return ResourceManager.GetString("NewTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordinal number of round:.
        /// </summary>
        public static string OrdinalNumberOfRound {
            get {
                return ResourceManager.GetString("OrdinalNumberOfRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to point.
        /// </summary>
        public static string Point {
            get {
                return ResourceManager.GetString("Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to points.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to points.
        /// </summary>
        public static string PointsMiddle {
            get {
                return ResourceManager.GetString("PointsMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        public static string PointsOfPlayer {
            get {
                return ResourceManager.GetString("PointsOfPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution preview.
        /// </summary>
        public static string PreviewSolution {
            get {
                return ResourceManager.GetString("PreviewSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to round.
        /// </summary>
        public static string Round {
            get {
                return ResourceManager.GetString("Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every two cells in the knight step cannot contain the same digit..
        /// </summary>
        public static string RulesAntiknight {
            get {
                return ResourceManager.GetString("RulesAntiknight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number in the circle is the sum of all numbers along the corresponding arrow..
        /// </summary>
        public static string RulesArrows {
            get {
                return ResourceManager.GetString("RulesArrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With small circles are marked all pairs of adjacent consecutive numbers..
        /// </summary>
        public static string RulesConsecutive {
            get {
                return ResourceManager.GetString("RulesConsecutive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number in a circle tells the difference between the two adjacent numbers..
        /// </summary>
        public static string RulesDifference {
            get {
                return ResourceManager.GetString("RulesDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 9 cells in the same position in outlined boxes contain numbers 1 to 9..
        /// </summary>
        public static string RulesDisjointGroups {
            get {
                return ResourceManager.GetString("RulesDisjointGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers in cells with circles are even..
        /// </summary>
        public static string RulesEven {
            get {
                return ResourceManager.GetString("RulesEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same numbers cannot repeat in grey regions..
        /// </summary>
        public static string RulesExtraRegions {
            get {
                return ResourceManager.GetString("RulesExtraRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All numbers have to comply with given inequality signs..
        /// </summary>
        public static string RulesGreaterThan {
            get {
                return ResourceManager.GetString("RulesGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill the grid with digits 1 to 9, so that each digit appears once in every row, column and outlined box..
        /// </summary>
        public static string RulesIrregular {
            get {
                return ResourceManager.GetString("RulesIrregular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the grid are placed cages. For every cage is given the sum of all numbers in the cage. Moreover, numbers in the cage cannot repeat..
        /// </summary>
        public static string RulesKiller {
            get {
                return ResourceManager.GetString("RulesKiller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All pairs of two neighboring numbers where one number is double the size of the second number are marked with a black circle. All pairs of two neighboring numbers where their difference is one are marked with a white circle. Between numbers 1 and 2 is placed black circle..
        /// </summary>
        public static string RulesKropki {
            get {
                return ResourceManager.GetString("RulesKropki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same digits cannot repeat on the main diagonals. Numbers around the grid tell the sum of all numbers along the corresponding diagonal in the direction of the arrow. Numbers in these sums can repeat..
        /// </summary>
        public static string RulesLittleKiller {
            get {
                return ResourceManager.GetString("RulesLittleKiller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers around the grid are neighbours of the number nine in a given row, column. Numbers are given by number size..
        /// </summary>
        public static string RulesNextToNine {
            get {
                return ResourceManager.GetString("RulesNextToNine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every two adjacent cells cannot contain consecutive numbers..
        /// </summary>
        public static string RulesNonconsecutive {
            get {
                return ResourceManager.GetString("RulesNonconsecutive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers in cells with squares are odd..
        /// </summary>
        public static string RulesOdd {
            get {
                return ResourceManager.GetString("RulesOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers around the grid are placed among the first three numbers from the edge in the given direction..
        /// </summary>
        public static string RulesOutside {
            get {
                return ResourceManager.GetString("RulesOutside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers along the grey lines create palindromes..
        /// </summary>
        public static string RulesPalindromes {
            get {
                return ResourceManager.GetString("RulesPalindromes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every arrow shows the direction in which the corresponding row or column placed number nine. Moreover, the number in the cell with the arrow tells the count of steps to this nine..
        /// </summary>
        public static string RulesSearchNine {
            get {
                return ResourceManager.GetString("RulesSearchNine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers along the grey lines create sequences. From one end always increases by the same step..
        /// </summary>
        public static string RulesSequences {
            get {
                return ResourceManager.GetString("RulesSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers in the grid present skyscrapers. Numbers around the grid tell the count of visible skyscrapers in a given direction. A higher skyscraper hides all the lower skyscrapers behind him..
        /// </summary>
        public static string RulesSkyscrapers {
            get {
                return ResourceManager.GetString("RulesSkyscrapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers around the grid tell the product of all numbers in cells with a star in a given row or column..
        /// </summary>
        public static string RulesStarProduct {
            get {
                return ResourceManager.GetString("RulesStarProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number in a circle tells the sum between the two adjacent numbers..
        /// </summary>
        public static string RulesSum {
            get {
                return ResourceManager.GetString("RulesSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers along with the thermometer increase (not necessarily by 1) in the direction from bulb to the opposite end..
        /// </summary>
        public static string RulesThermometers {
            get {
                return ResourceManager.GetString("RulesThermometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same numbers cannot touch and not with corners..
        /// </summary>
        public static string RulesUntouchable {
            get {
                return ResourceManager.GetString("RulesUntouchable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All pairs of two neighboring numbers with sum 5 are marked with V and all pairs of two neighboring numbers with sum 10 are marked with X..
        /// </summary>
        public static string RulesXVSudoku {
            get {
                return ResourceManager.GetString("RulesXVSudoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second sudoku.
        /// </summary>
        public static string SecondSudoku {
            get {
                return ResourceManager.GetString("SecondSudoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file.
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of grid.
        /// </summary>
        public static string SizeOfGrid {
            get {
                return ResourceManager.GetString("SizeOfGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution:.
        /// </summary>
        public static string Solution {
            get {
                return ResourceManager.GetString("Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation of solution.
        /// </summary>
        public static string SolutionCalculation {
            get {
                return ResourceManager.GetString("SolutionCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to solutions.
        /// </summary>
        public static string SolutionPlural {
            get {
                return ResourceManager.GetString("SolutionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to solution.
        /// </summary>
        public static string SolutionSingular {
            get {
                return ResourceManager.GetString("SolutionSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create booklet.
        /// </summary>
        public static string StartScreenButtonCreateBooklet {
            get {
                return ResourceManager.GetString("StartScreenButtonCreateBooklet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create sudoku.
        /// </summary>
        public static string StartScreenButtonCreateSudoku {
            get {
                return ResourceManager.GetString("StartScreenButtonCreateSudoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open booklet.
        /// </summary>
        public static string StartScreenButtonOpenBooklet {
            get {
                return ResourceManager.GetString("StartScreenButtonOpenBooklet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open sudoku.
        /// </summary>
        public static string StartScreenButtonOpenSudoku {
            get {
                return ResourceManager.GetString("StartScreenButtonOpenSudoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudoku.
        /// </summary>
        public static string Sudoku {
            get {
                return ResourceManager.GetString("Sudoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antiknight.
        /// </summary>
        public static string SudokuAntiknight {
            get {
                return ResourceManager.GetString("SudokuAntiknight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow Sudoku.
        /// </summary>
        public static string SudokuArrow {
            get {
                return ResourceManager.GetString("SudokuArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Kropki.
        /// </summary>
        public static string SudokuBlackKropki {
            get {
                return ResourceManager.GetString("SudokuBlackKropki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic sudoku.
        /// </summary>
        public static string SudokuClassic {
            get {
                return ResourceManager.GetString("SudokuClassic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consecutive.
        /// </summary>
        public static string SudokuConsecutive {
            get {
                return ResourceManager.GetString("SudokuConsecutive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagonal.
        /// </summary>
        public static string SudokuDiagonal {
            get {
                return ResourceManager.GetString("SudokuDiagonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference.
        /// </summary>
        public static string SudokuDifference {
            get {
                return ResourceManager.GetString("SudokuDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disjoint groups.
        /// </summary>
        public static string SudokuDisjointGroups {
            get {
                return ResourceManager.GetString("SudokuDisjointGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Even.
        /// </summary>
        public static string SudokuEven {
            get {
                return ResourceManager.GetString("SudokuEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Regions Sudoku.
        /// </summary>
        public static string SudokuExtraRegions {
            get {
                return ResourceManager.GetString("SudokuExtraRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater Than.
        /// </summary>
        public static string SudokuGreaterThan {
            get {
                return ResourceManager.GetString("SudokuGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudoku grid:.
        /// </summary>
        public static string SudokuGrid {
            get {
                return ResourceManager.GetString("SudokuGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudoku has.
        /// </summary>
        public static string SudokuHas {
            get {
                return ResourceManager.GetString("SudokuHas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irregular.
        /// </summary>
        public static string SudokuIrregular {
            get {
                return ResourceManager.GetString("SudokuIrregular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killer.
        /// </summary>
        public static string SudokuKiller {
            get {
                return ResourceManager.GetString("SudokuKiller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kropki.
        /// </summary>
        public static string SudokuKropki {
            get {
                return ResourceManager.GetString("SudokuKropki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Little Killer Sudoku.
        /// </summary>
        public static string SudokuLittleKiller {
            get {
                return ResourceManager.GetString("SudokuLittleKiller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next To Nine.
        /// </summary>
        public static string SudokuNextToNine {
            get {
                return ResourceManager.GetString("SudokuNextToNine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nonconsecutive.
        /// </summary>
        public static string SudokuNonconsecutive {
            get {
                return ResourceManager.GetString("SudokuNonconsecutive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odd.
        /// </summary>
        public static string SudokuOdd {
            get {
                return ResourceManager.GetString("SudokuOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outside sudoku.
        /// </summary>
        public static string SudokuOutside {
            get {
                return ResourceManager.GetString("SudokuOutside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palindrome.
        /// </summary>
        public static string SudokuPalindrome {
            get {
                return ResourceManager.GetString("SudokuPalindrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points:.
        /// </summary>
        public static string SudokuPoints {
            get {
                return ResourceManager.GetString("SudokuPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules:.
        /// </summary>
        public static string SudokuRules {
            get {
                return ResourceManager.GetString("SudokuRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Nine.
        /// </summary>
        public static string SudokuSearchNine {
            get {
                return ResourceManager.GetString("SudokuSearchNine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        public static string SudokuSequence {
            get {
                return ResourceManager.GetString("SudokuSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid size.
        /// </summary>
        public static string SudokuSizeWindowTitle {
            get {
                return ResourceManager.GetString("SudokuSizeWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skyscrapers.
        /// </summary>
        public static string SudokuSkyscrapers {
            get {
                return ResourceManager.GetString("SudokuSkyscrapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Products.
        /// </summary>
        public static string SudokuStarProducts {
            get {
                return ResourceManager.GetString("SudokuStarProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string SudokuSum {
            get {
                return ResourceManager.GetString("SudokuSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermometers.
        /// </summary>
        public static string SudokuThermometer {
            get {
                return ResourceManager.GetString("SudokuThermometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untouchable.
        /// </summary>
        public static string SudokuUntouchable {
            get {
                return ResourceManager.GetString("SudokuUntouchable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White Kropki.
        /// </summary>
        public static string SudokuWhiteKropki {
            get {
                return ResourceManager.GetString("SudokuWhiteKropki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windoku.
        /// </summary>
        public static string SudokuWindoku {
            get {
                return ResourceManager.GetString("SudokuWindoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XV sudoku.
        /// </summary>
        public static string SudokuXV {
            get {
                return ResourceManager.GetString("SudokuXV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported sudoku.
        /// </summary>
        public static string SupportedSudoku {
            get {
                return ResourceManager.GetString("SupportedSudoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time for solving:.
        /// </summary>
        public static string TimeForSolving {
            get {
                return ResourceManager.GetString("TimeForSolving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total points: .
        /// </summary>
        public static string TotalPoints {
            get {
                return ResourceManager.GetString("TotalPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported sudoku.
        /// </summary>
        public static string UnsupportedSudoku {
            get {
                return ResourceManager.GetString("UnsupportedSudoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each grey region contains digits 1 to 9..
        /// </summary>
        public static string WindokuRules {
            get {
                return ResourceManager.GetString("WindokuRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with given numbers.
        /// </summary>
        public static string WithGivenNumbers {
            get {
                return ResourceManager.GetString("WithGivenNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to without given numbers.
        /// </summary>
        public static string WithoutGivenNumbers {
            get {
                return ResourceManager.GetString("WithoutGivenNumbers", resourceCulture);
            }
        }
    }
}
